{
    "category": "Sale Order Customization",
    "name": "Sale Order Customization",
    "license": "AGPL-3",
    "author": "WaoConnect",
    "sequence": 1,
    "demo": [],
    "summary": "Sale Order Customization",
    "application": True,
    "depends": ['sale_management','sale_quotation_builder'],
    "version": "15.10",
    "auto_install": False,
    "data": ['data/cron.xml', 'views/sale_order.xml', 'views/sale_portal_template.xml', 'views/report_sale_order.xml'],
    "installable": True,
}
